"""create all tables in kakeibo schema

Revision ID: 571101ecf88f
Revises: 
Create Date: 2025-02-25 14:32:11.714756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571101ecf88f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(), nullable=False),
    sa.Column('required_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('level_id'),
    schema='kakeibo'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('continuous_login_days', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_login_days', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_level'], ['kakeibo.user_levels.level_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    schema='kakeibo'
    )
    op.create_index(op.f('ix_kakeibo_users_email'), 'users', ['email'], unique=True, schema='kakeibo')
    op.create_index(op.f('ix_kakeibo_users_user_id'), 'users', ['user_id'], unique=False, schema='kakeibo')
    op.create_index(op.f('ix_kakeibo_users_username'), 'users', ['username'], unique=True, schema='kakeibo')
    op.create_table('major_categories',
    sa.Column('major_category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='categorytype', schema='kakeibo'), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['kakeibo.users.user_id'], ),
    sa.PrimaryKeyConstraint('major_category_id'),
    schema='kakeibo'
    )
    op.create_index(op.f('ix_kakeibo_major_categories_major_category_id'), 'major_categories', ['major_category_id'], unique=False, schema='kakeibo')
    op.create_table('minor_categories',
    sa.Column('minor_category_id', sa.Integer(), nullable=False),
    sa.Column('major_category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['major_category_id'], ['kakeibo.major_categories.major_category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kakeibo.users.user_id'], ),
    sa.PrimaryKeyConstraint('minor_category_id'),
    schema='kakeibo'
    )
    op.create_index(op.f('ix_kakeibo_minor_categories_minor_category_id'), 'minor_categories', ['minor_category_id'], unique=False, schema='kakeibo')
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('major_category_id', sa.Integer(), nullable=True),
    sa.Column('minor_category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['major_category_id'], ['kakeibo.major_categories.major_category_id'], ),
    sa.ForeignKeyConstraint(['minor_category_id'], ['kakeibo.minor_categories.minor_category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kakeibo.users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    schema='kakeibo'
    )
    op.create_index(op.f('ix_kakeibo_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False, schema='kakeibo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kakeibo_transactions_transaction_id'), table_name='transactions', schema='kakeibo')
    op.drop_table('transactions', schema='kakeibo')
    op.drop_index(op.f('ix_kakeibo_minor_categories_minor_category_id'), table_name='minor_categories', schema='kakeibo')
    op.drop_table('minor_categories', schema='kakeibo')
    op.drop_index(op.f('ix_kakeibo_major_categories_major_category_id'), table_name='major_categories', schema='kakeibo')
    op.drop_table('major_categories', schema='kakeibo')
    op.drop_index(op.f('ix_kakeibo_users_username'), table_name='users', schema='kakeibo')
    op.drop_index(op.f('ix_kakeibo_users_user_id'), table_name='users', schema='kakeibo')
    op.drop_index(op.f('ix_kakeibo_users_email'), table_name='users', schema='kakeibo')
    op.drop_table('users', schema='kakeibo')
    op.drop_table('user_levels', schema='kakeibo')
    # ### end Alembic commands ###
