"""Add user profile fields

Revision ID: 947f679e2cb9
Revises: fb81a0fbaeee
Create Date: 2025-03-11 20:44:12.897921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947f679e2cb9'
down_revision: Union[str, None] = 'fb81a0fbaeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_composition', sa.Integer(), nullable=True), schema='kakeibo')
    op.add_column('users', sa.Column('age_group', sa.Integer(), nullable=True), schema='kakeibo')
    op.add_column('users', sa.Column('household_income_range', sa.Integer(), nullable=True), schema='kakeibo')
    op.add_column('users', sa.Column('lifestyle_mindset', sa.Integer(), nullable=True), schema='kakeibo')
    op.add_column('users', sa.Column('midterm_goal', sa.Integer(), nullable=True), schema='kakeibo')
    op.add_column('users', sa.Column('monthly_expense_target', sa.Numeric(precision=10, scale=2), nullable=True), schema='kakeibo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_expense_target', schema='kakeibo')
    op.drop_column('users', 'midterm_goal', schema='kakeibo')
    op.drop_column('users', 'lifestyle_mindset', schema='kakeibo')
    op.drop_column('users', 'household_income_range', schema='kakeibo')
    op.drop_column('users', 'age_group', schema='kakeibo')
    op.drop_column('users', 'family_composition', schema='kakeibo')
    # ### end Alembic commands ###
